### ISSUE TITLE
Fix Problem Statement file

### ISSUE THREAD

**Issue by DeeshaPatel** [DeeshaPatel/CAS-741-Solar-Cooker#1]
Dr @smiths, can you please check problem statement?

**Comment by smiths** [comment]
My feedback is as follows:
- please explicitly assign me to issues like this in the future
- please include a link to the artifact being reviewed in the future
- please include at least one reference in your problem statement.  Specifically, the reference that you used to inspire the project
- The inputs and outputs section is too vague.  You should be abstract, but I need a better feel for what you expect to input and output.  Look at the above-mentioned paper and characterize the inputs that they are providing and the outputs.  Is the output really the energy consumed?

I'll change the assignment of the issue to you.  Once you have made the requested change, you can reassign the issue to me, or create a new issue.  Once I close the issue, I'll approve your project in the Repos.csv file.

**Comment by DeeshaPatel** [comment]
@smiths I don't find any attached link with above comment. Can you please comment it again? Or Is it the same that we discussed and confirmed over mail?

**Comment by smiths** [comment]
In future issues I would like you to include a link for me to quickly find your problem statement, like for this [issue](https://github.com/joedf/CAS741_w23/issues/1).

**Comment by DeeshaPatel** [comment]
@smiths  Thank you so much for correcting me. I have updated [ProblemStatement.pdf](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/blob/ff5af0be6a8109cd856fb91627eb87440a92f5f3/docs/ProblemStatementAndGoals/ProblemStatement.pdf) file according to your suggestions. If you find any problem with it, please correct me.

**Comment by smiths** [comment]
@DeeshaPatel, in the future, please include links to the commits that were made to address an issue.  You can do this by pasting the commit hash into your comment, like this ff5af0be6a8109cd856fb91627eb87440a92f5f3.

**Comment by smiths** [comment]
Looks good @DeeshaPatel.  For your output, I would just say the temperature of the solar box over time, but I won't ask you to do another iteration.  :smile:  Your project is approved!  :smile:
