### ISSUE TITLE
Issues about the last part SRS

### ISSUE THREAD

**Issue by MinMah23** [DeeshaPatel/CAS-741-Solar-Cooker#10]
- [x] In section 5.2, describe about the non-functional requirement, for example about the details of the requirements.
- [x] In section6, please correct "as a part of energy".
- [x] In section 7, the label is "LC3" which should be like UC1.
- [x] In section 7, you mentioned "int2" which is not described through the document.
- [x] I think Table 4 needs some review, for example T2  is connected with A4. why the assumptions are not connected to other components except A1?
- [x] As I understood, you delete some parts of the template, I quote what prof. Smith told about the same situation: "For a section of a template, if you don't use it, keep the title and enter "Not applicable". If it isn't obvious, explain why the section is not applicable. I don't think I explicitly mentioned this in class, but with a standard template you don't want to delete sections. If someone reads the document and a section is missing, they don't know if the author forgot the section, or intentionally removed it." so please consider that.

**Comment by DeeshaPatel** [comment]
For your last comment, I just removed the unnecessary things which were optional. I am not sure about it.

**Comment by DeeshaPatel** [comment]
I have done updating [SRS.pdf](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/blob/5f9c145f6a1ad6e9054e4acb6aec4d1042d6dd9f/docs/SRS/SRS.pdf) for issue #10 and can be tracked using [5f9c145](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/commit/5f9c145f6a1ad6e9054e4acb6aec4d1042d6dd9f)
