### ISSUE TITLE
VnV Ready for Review

### ISSUE THREAD

**Issue by DeeshaPatel** [DeeshaPatel/CAS-741-Solar-Cooker#11]
Hello prof. I've done my [VnV](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/blob/f5b15687c5f5ecc00eb81b42cb4f06871b428b3c/docs/VnVPlan/VnVPlan.pdf). I will create an issue for Primary reviewer and Secondary reviewer separately. Thank you so much for extending my deadline.

**Comment by smiths** [comment]
Thank you @DeeshaPatel.  I'll assign this issue to me.

**Comment by smiths** [comment]
Feedback is provided in 2a6c017.
