### ISSUE TITLE
VnV Ready for Review - Mina

### ISSUE THREAD

**Issue by DeeshaPatel** [DeeshaPatel/CAS-741-Solar-Cooker#12]
@MinMah23 My VnV plan is ready to review. You can find [VnVPlan](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/blob/f5b15687c5f5ecc00eb81b42cb4f06871b428b3c/docs/VnVPlan/VnVPlan.pdf) here.

**Comment by MinMah23** [comment]
Dear @DeeshaPatel,
I've done my review. Thank you.

**Comment by DeeshaPatel** [comment]
Thank you so much dear.
