### ISSUE TITLE
VnV Ready for Review - Lesley

### ISSUE THREAD

**Issue by DeeshaPatel** [DeeshaPatel/CAS-741-Solar-Cooker#13]
@LesleyWheat My VnV Plan ready for review. I am open to comments. You can find [VnVPlan](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/blob/f5b15687c5f5ecc00eb81b42cb4f06871b428b3c/docs/VnVPlan/VnVPlan.pdf) here.

**Comment by LesleyWheat** [comment]
Done, I did not have time to list all the typos so I suggest you reread it.

**Comment by DeeshaPatel** [comment]
Ok. Thank you so much dear for your helpful suggestions. Closing this issue.
