### ISSUE TITLE
typo issues-part1

### ISSUE THREAD

**Issue by MinMah23** [DeeshaPatel/CAS-741-Solar-Cooker#14]
- [x] In Revision History table, correct "section" to "sections"
- [x] The paragraph before the General Information, verification and validation should be in camel?
- [x]  Section 3.2, "-" should be omitted.
- [x] In Section 3.2, you wrote "a test
matrix with detailed mapping connecting the testing performed to the system
requirements.", change "testing" to "tests".
- [x] In Section 4: you wrote "This section describes the plan for the Solar Cooker Energy Calculator system." but it's better to mention what is the plan for?
- [x] Design and Implementation in this section should not start with uppercase.
- [x] According to writing checklist, correct the "Dr. Spencer Smith " to avoid extra space.

**Comment by DeeshaPatel** [comment]
I have done the changes according to the comments. [12fc698](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/commit/12fc6984dde29f849c9e5394f1ab4208edf4719a)
