### ISSUE TITLE
Part1 issues, pages 1 and 2

### ISSUE THREAD

**Issue by MinMah23** [DeeshaPatel/CAS-741-Solar-Cooker#15]
- [x] The paragraph before the General Information, you mentioned that the document is for ensuring the requirements and goals of the program, but in fact it tries to test if all the software meets all the requirement or not.
- [x] In section 3.2, why you wrote "The specific goal of this document is to demonstrate the adequate
usability of the system.", why testing usability would be the specific goal?
- [x] In Table 1, for the author, you specified the details about VnV while you haven't mention about the process after getting feedbacks from reviewers.
- [x] In Table1, for domain expert, I thin it's better to delete "review the VnV plan." while her responsibility is to review all the docs and you wrote it.

**Comment by DeeshaPatel** [comment]
For your first comment, I guess ensure the requirements can be an alternative to say testing.

**Comment by DeeshaPatel** [comment]
For your second comment, I am aiming to have at least usable system at the end. So, I think usability of the system can be important part.

**Comment by DeeshaPatel** [comment]
@MinMah23  If my comments feels you ok for the comment 1 and comment 2, we can close this issue.

**Comment by MinMah23** [comment]
> For your first comment, I guess ensure the requirements can be an alternative to say testing.
Well, I respect your idea, however, I still think it can be written in better way. That's OK, you can close it, if you are sure about it.

**Comment by MinMah23** [comment]
> For your second comment, I am aiming to have at least usable system at the end. So, I think usability of the system can be important part.

Yes, I see what you are saying but pay attention that section 3.2 is for objectives of the document.

**Comment by DeeshaPatel** [comment]
Perfect. I done changes for it. Thank you dear.
