### ISSUE TITLE
issues on pages 3 to 7

### ISSUE THREAD

**Issue by MinMah23** [DeeshaPatel/CAS-741-Solar-Cooker#16]
- [x] In section 4.2, step 1, you wrote yourself as the assigned reviewers, I think it's better to delete it.
- [x] In section 5.1.1 and output part, you wrote "Give an appropriate error message defined in the Table 2" while the first row of table does not make an error.
- [x]  I suggest to add empty values as an error in table 2 for inputs.
- [x] In "Functional tests - Input tests - Temperature value" section, test cases TC-SCEC-1-2 to TC-SCEC-1-5 are given but in table 3,test cases names are 2-1 to 2-5.
- [x] In  "Functional tests - Input tests - other parameters" section, the input is temperature as the previous test but you wanted to have emittance as input, according to table 4.
- [x] In test case derivation at the same part, again , test cases TC-SCEC-1-2 to TC-SCEC-1-5 are given but in table 4,test cases names are 3-1 to 3-4. 
- [x] In test case derivation at the same part, first and second rows don't make an error as input.

**Comment by DeeshaPatel** [comment]
1. I also need to review my work before submitting it. :)

**Comment by DeeshaPatel** [comment]
[80e2016](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/commit/80e2016fc1fbc554f6758c53ad94b421742c46a7) I have done these changes.
