### ISSUE TITLE
issues on pages 8 to 11

### ISSUE THREAD

**Issue by MinMah23** [DeeshaPatel/CAS-741-Solar-Cooker#17]
- [x] In section 5.1.2, both of the tests are combination of automatic and manual, in "How test will be performed:" you just mentioned the way of performing automatic part.
- [x] In section 5.2, you wrote "Functional requirements for SCEC are given in SRS section 5.2. There are 5
functional requirements for SCEC." but it's the non functional requirement section.
- [x] In sections 5.2.1 to 5.2.4, It's better to review the input/out parts again, for example, what is the output of each test?
- [x] In 5.2.2, what are the team members? the same as VnV team?
- [x] In 5.2.3, mention the reference of usability survey.

**Comment by DeeshaPatel** [comment]
For your last comment, I don't use any website or any other media for the questionnaire. I just think about it and listed. 😅

**Comment by DeeshaPatel** [comment]
I have done changes for this issues in [624c4d9](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/commit/624c4d9830e5453c905e1b7ba2f3032a55e132d5).
