### ISSUE TITLE
typo issues-part2

### ISSUE THREAD

**Issue by MinMah23** [DeeshaPatel/CAS-741-Solar-Cooker#18]
- [x] In section 4.2, step 2, change "the issue" to  "an issue"
- [x] In section 4.3, "Domain/ Primary" and "Secondary Reviewer" should not start with camel.
- [x] In section 4.4, it's better to mention the section related in SRS file.
- [x] Section 4.5, it is a bulleted list while it is one part.
- [x] In section 5.1, correct "5" because: All numbers from zero to ten should be written out as words.
- [x] In section 5.1.1, the name of test should be in capital letter.
- [x] In table 6, omit ")" after Answer heading.
- [x] In 5.2.4, it should be operating systems.

**Comment by DeeshaPatel** [comment]
[ac9e9f5](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/commit/ac9e9f543fc1bcdd92cbdc809fd8d130268bb13e) is related to the changes in this issue.
