### ISSUE TITLE
SRS Document Review

### ISSUE THREAD

**Issue by DeeshaPatel** [DeeshaPatel/CAS-741-Solar-Cooker#2]
Dr. @smiths, I have completed my [SRS.pdf](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/blob/c30e942c237b68373a13c63a020ee41c93fa5e50/docs/SRS/SRS.pdf) file. Can you please review and let me know if I missed anything? 

Thank you so much.

**Comment by smiths** [comment]
Thank you @DeeshaPatel.

**Comment by DeeshaPatel** [comment]
@MinMah23 @KarenKarenWang My [SRS](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/blob/3c01945581ebf857306e7ec673fa158f392714d1/docs/SRS/SRS.pdf) is ready to review.

**Comment by MinMah23** [comment]
Dear @DeeshaPatel,
I want to thank your efforts, I really appreciate that.
I've done my review : ),I've made some suggestion to make it better, hope that it'll be helpful.

**Comment by smiths** [comment]
A marked-up copy of the SRS with my feedback is available in 7c53c8d.

**Comment by DeeshaPatel** [comment]
Thank you so much prof @smiths for the useful feedback.
