### ISSUE TITLE
VnV Plan: Deleted section

### ISSUE THREAD

**Issue by LesleyWheat** [DeeshaPatel/CAS-741-Solar-Cooker#20]
"4.4 Verification and Validation Plan Verification Plan" is not present in the document.

**Comment by DeeshaPatel** [comment]
Done. Added. [3fbe1eb](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/commit/3fbe1eb21ef03dff7dffd9007176e3c26e5ca7bc)
