### ISSUE TITLE
VnV Plan: Section links

### ISSUE THREAD

**Issue by LesleyWheat** [DeeshaPatel/CAS-741-Solar-Cooker#21]
![image](https://user-images.githubusercontent.com/29044132/220668080-b953448f-c92f-4756-8810-bf642c01be6d.png)

You should be using \label{} and \ref{} to generate section numbers to say "Section 5.1.1" rather than "subsubsection 5.1.1".

**Comment by DeeshaPatel** [comment]
Perfect. I thought to be more specific for subsections. But it's ok to change it to section.
