### ISSUE TITLE
VnV Plan 5.1.2: Latex formatting

### ISSUE THREAD

**Issue by LesleyWheat** [DeeshaPatel/CAS-741-Solar-Cooker#24]
![image](https://user-images.githubusercontent.com/29044132/220670518-5dac5d03-c8ac-4ced-96d7-ca853612d1cb.png)

You probably want $T_{g2}$ not $T_g2$, write as T_{g2} to get $T_{g2}$.

**Comment by DeeshaPatel** [comment]
Oh yeah! My bad. Thank you. Done
