### ISSUE TITLE
VnV Plan 5.2.1: Understandability

### ISSUE THREAD

**Issue by LesleyWheat** [DeeshaPatel/CAS-741-Solar-Cooker#25]
![image](https://user-images.githubusercontent.com/29044132/220671473-f6414066-a9bf-43c1-8673-72b64ff41432.png)

I would argue more comments does not mean the code is more readable or understandable. There is a whole debate but having comments that are repeating information that is already obvious is generally poor practice.

> The name of the variables and method is meaningful.

This is a good check.

> The whole code indented properly to understand the flow.

This does not make any sense imo, you could say something along the lines of consistent formatting but code indenting does not help the reader "understand the flow". What "the flow" is here is not clear?

> Different comments is useful to understand the importance of code.

Also, not sure what this means but I think I disagree.

> Overall quality.

Ok, sure that's relevant but very vague and super subjective.

**Comment by DeeshaPatel** [comment]
1. For first question, comments in the sense of review work. I think I should use different word here. 
2. I think flow is a wrong word. I should say "code". Thanks for it. 

Done.
