### ISSUE TITLE
VnV Plan Typos

### ISSUE THREAD

**Issue by LesleyWheat** [DeeshaPatel/CAS-741-Solar-Cooker#26]
There are more probably but this is just what I noticed.

3.3: Missing period at end of sentence
Table 1 "Document" : "All" not "all"
Table 1 "Description" : "Create and manage all the documents, provide the VnV plan, test case and test execution, verify the implementation." should be "Create all documentation, manage all documentation, create the VnV plan, preform the VnV testing."
4.4: "An author will share the copy of the original code with Domain expert and then domain expert will manually test the code with different test cases." should have "domain expert" not "Domain expert". Also, there is only one author.
4.4: "The domain expert will raise the issue in GitHub if finds any issue with the code." missing pronoun of  should be "if they find"
4.5: "These tests are performed by predetermining user inputs and comparing it with expected values." Wrong verb tenses.
Table 5: "The name of the variables and method is meaningful." should be "names" and "methods" with an s
Table 5: "Task are well broken into function." does not make sense

**Comment by DeeshaPatel** [comment]
I have done this changes in [eb70cfd](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/commit/eb70cfd9a35c473de4aa77d944697ce580ceda74)
