### ISSUE TITLE
Issues for questions on feedback 

### ISSUE THREAD

**Issue by DeeshaPatel** [DeeshaPatel/CAS-741-Solar-Cooker#27]
I asked Mina for my code walkthrough part. She agreed for it. 

I have some questions. Please prof. @smiths guide me. 

In Static testing method: 

I mentioned it is code walkthrough. But after reading different code review methods,  I guess it's more like "Over-the-shoulder reviews". Because in this method, author show and explain the code to the reviewer and reviewer can ask questions or makes suggestions for the code. If I am wrong please correct me.

**Comment by smiths** [comment]
A code walkthrough is a meeting where you present your code to someone else.  You don't do it as you are writing the code, but when it is done.  You don't run the code for the code review.  Instead you walkthrough it manually.  Often it would be a walkthrough on paper, but it could be on a whiteboard or a blackboard.  You make note of the values of variables and how they change as you step through the code one line at a time.  You and the reviewer are essentially pretending to be a the computer and keeping track of its state.  The benefit is that as  you describe the code and walk through it problems are potentially revealed.

You don't have to walk through the entire code, just the most important parts.

The "over the shoulder review" sounds more like something you would do for reviewing a single change request.

That is great that Mina has agreed to help!

You will want to take meeting notes from your code review meeting.  Of particular relevance are any problems you note.

Some links for code walkthroughs are as follows:

https://www.educative.io/answers/what-is-code-walkthrough-in-software-engineering

https://tutorialsinhand.com/tutorials/software-engineering-tutorial/software-coding/code-walkthrough.aspx

**Comment by DeeshaPatel** [comment]
Thank you so much dear prof. for detailed description.

**Comment by smiths** [comment]
The question was answered, so we can close this issue.
