### ISSUE TITLE
MG and MIS Ready for review 

### ISSUE THREAD

**Issue by DeeshaPatel** [DeeshaPatel/CAS-741-Solar-Cooker#28]
Hello dear prof, 

My [MG](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/blob/main/docs/Design/SoftArchitecture/MG.pdf) and [MIS](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/blob/main/docs/Design/SoftDetailedDes/MIS.pdf) are ready to review. Thank you for constant guidance. :)

**Comment by smiths** [comment]
Great! Thank you @DeeshaPatel.  I'm looking forward to reviewing your work.  :smile:

**Comment by smiths** [comment]
Hello @DeeshaPatel.   Here are the marked-up versions of the MG and MIS.

[MG.pdf](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/files/11193970/MG.pdf)

[MIS.pdf](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/files/11193971/MIS.pdf)
