### ISSUE TITLE
Rephrasing UC4 and UC5 in MG

### ISSUE THREAD

**Issue by samm82** [DeeshaPatel/CAS-741-Solar-Cooker#32]
I wonder if it makes more sense to merge UC4 and UC5 into one UC saying what the goals are. Alternatively, instead of saying "the" goal, these UCs should say "a" goal, since there are more than one. Regardless, the word "another" should be removed; as is it is grammatically incorrect, but even if it was reworded, it doesn't really contribute much.

**Comment by DeeshaPatel** [comment]
Ok
