### ISSUE TITLE
Input should not be included in Semantics sections of MIS

### ISSUE THREAD

**Issue by samm82** [DeeshaPatel/CAS-741-Solar-Cooker#35]
When specifying the semantics of an access routine or local function, the input is not described; its type is denoted in the table (if an access routine) or in its type description (if a local function), and any relevant information is describing in terms of how it affects the transition or the output.

**Comment by DeeshaPatel** [comment]
I got your point and I guess I did mistake in @MinMah23's review. Please @MinMah23 ignore comments related to the input parts in MIS. Thanks @samm82 for correcting me. I also checked [document](https://gitlab.cas.mcmaster.ca/smiths/se2aa4_cs2me3/-/blob/master/Assignments/A3/A3P1_Spec.pdf). Thanks.

**Comment by DeeshaPatel** [comment]
Done. Sorry @MinMah23. I realised my mistake.
