### ISSUE TITLE
Issues with Energy Equation Module

### ISSUE THREAD

**Issue by samm82** [DeeshaPatel/CAS-741-Solar-Cooker#37]
_A lot of these issues come up throughout the modules, so I'm just going to describe them in the context of this one module (at least for now), but you should go over these for all the modules and make the changes where relevant._

- [x] In the Exported Access Programs table, the In and Out columns should only include the types of the values, not their names.
- [x] Since this module has no state variables, there can't be a transition from any of its module (these should be outputs).
- [x] This new output can be specified a lot more compactly: $\text{out} := \\langle i \in \mathbb{N}, 0 \leq i < |\text{temp}| \~|\~ m_f c_f (\text{temp}[i] - T_\text{init}) \\rangle, \text{ where } m_f = \dots$
   - This may not be exactly right, and you may want to represent it slightly differently, but steps 2 to 5 can for sure be represented in one expression.
   - I'm also not sure if you need the local function at all; you may just be able to represent $m_f$ and $c_f$ like so, although you might want to double check with @smiths.
      - [x] If you decide to keep it, local functions are defined with slightly different notation and should include their type information. (See [here](https://gitlab.cas.mcmaster.ca/smiths/se2aa4_cs2me3/-/blob/master/Assignments/PreviousYears/2020/A2-ChemReacts/A2.pdf) for an example).
- [x] There are some grammatical/consistency issues with the Description column; I'm not sure if this column is even needed, since this information can be deduced from the expressions themselves.
- [x] The next module (the Input Format Module) should start on a new page.

**Comment by DeeshaPatel** [comment]
I prefer to keep local function. Also, I prefer to keep description column for better understanding of the error message. I'll try to reduce the grammatical mistakes. 😅
