### ISSUE TITLE
Issues with Output Format Module

### ISSUE THREAD

**Issue by samm82** [DeeshaPatel/CAS-741-Solar-Cooker#39]
In addition to relevant issues from #37:

- [x] The type "time vector" is never defined; this should likely be a sequence of numbers.
- [x] Why is the time vector needed to output the temperature and energy sequences? If it is outputted as well, then it should be added to the output of the `output()` function; otherwise, it should be removed as an input.
- [x] `fileName` is not an environment variable; it is an actual variable that exists within your program that is passed. The appropriate environment variable would (I believe) be the file itself.
- [x] I'm pretty sure that these exceptions will be caught by the program itself and don't need to be defined by you.
- [x] The description of a `FileAlreadyExistError` is "Change the name of the file or require permission to override the content." If this is behaviour that your program will perform, then it should be specified in its output.

**Comment by DeeshaPatel** [comment]
I need time vector for plot the graph. As my output module uses Plot module, I need time vector.
