### ISSUE TITLE
Issues with Introduction

### ISSUE THREAD

**Issue by MinMah23** [DeeshaPatel/CAS-741-Solar-Cooker#4]
- [x] I found some inconsistency in use of Solar and some other words, I’ve highlighted those for you. Please check this through your document.
![image](https://user-images.githubusercontent.com/121309168/217696379-9754ca4e-ef2e-4fe8-9737-be01a28b1e1c.png)
- [x]  You wrote “It is indeed a fact that the demand for renewable energy has increased to deal with the problem.”, but what’s the problem that you’ve mentioned?
- [x]  It is better to say: several designs have been proposed.

**Comment by DeeshaPatel** [comment]
Dear @MinMah23, Thank you so much for your clear and useful suggestions. 

But for your last suggestions, I think algorithm is perfect word. The reason is that I am comparing algorithms not design of the Solar Cooker.
