### ISSUE TITLE
Notation for Declaring State Variables in MIS

### ISSUE THREAD

**Issue by samm82** [DeeshaPatel/CAS-741-Solar-Cooker#40]
When defining state variables, you should follow the appropriate notation, only including the type information. (I would still keep comments that describe what they are in the case of having many of them, like in your Temperature ODEs Module.)

![image](https://user-images.githubusercontent.com/35857611/226146646-b581d5e9-8839-479e-8bdb-a3601e1ac422.png)
[source](https://gitlab.cas.mcmaster.ca/smiths/se2aa4_cs2me3/-/blob/master/Assignments/PreviousYears/2020/A2-ChemReacts/A2.pdf)

**Comment by DeeshaPatel** [comment]
You mean to change my notation from ":= / ∈" to just ":"?

**Comment by DeeshaPatel** [comment]
Done.

**Comment by samm82** [comment]
> You mean to change my notation from ":= / ∈" to just ":"?

Yes, I would. While "∈" isn't technically wrong, I would just use ":" to stick with consistent notation.

**Comment by DeeshaPatel** [comment]
Thanks dear @samm82 for your help 😊.
