### ISSUE TITLE
LaTeX words in math mode

### ISSUE THREAD

**Issue by samm82** [DeeshaPatel/CAS-741-Solar-Cooker#41]
When writing out words in math mode (i.e., between dollar signs), use `\text{_}` so that LaTeX treats it as a word and not a bunch of variables being multiplied together (the main place this occurs is in the ODE Solver Module). You do this in some places, but not all.
![image](https://user-images.githubusercontent.com/35857611/226146722-4a8fda64-b0c5-4769-a48a-54823db18026.png)

**Comment by DeeshaPatel** [comment]
Done.
