### ISSUE TITLE
Issues with Plotting Result Module

### ISSUE THREAD

**Issue by samm82** [DeeshaPatel/CAS-741-Solar-Cooker#42]
In addition to the relevant issues from #37, the output of `plot()` shouldn't be a `TypeError`; my guess is that this was meant for the Exceptions column.

As far as #37 goes, note that while the transition of `plot()` should be its output (since there is no change of state), I think it makes the most sense to describe it as you already do, instead of trying to find some way to make it more mathematical.

**Comment by DeeshaPatel** [comment]
Done.
