### ISSUE TITLE
Fix notation for sequences, etc.

### ISSUE THREAD

**Issue by samm82** [DeeshaPatel/CAS-741-Solar-Cooker#43]
When I was working on my project, I wasn't sure about how to do this either lol - I would recommend looking at [this resource](https://gitlab.cas.mcmaster.ca/smiths/cas741/-/tree/master/Lectures/MathReviewPlusExample) from Dr. Smith's undergrad course he used to teach and follow this format.

For example, in the Temperature ODEs Module, I would represent the following as $\textit{tuple of }(T1 : \mathbb{R}, T2 : \mathbb{R})$ - there will only be two elements here, so it makes more sense to enforce this.
![image](https://user-images.githubusercontent.com/35857611/226147048-81402347-cbf7-46c5-b9c8-bb0024ac7e8a.png)

**Comment by DeeshaPatel** [comment]
Thanks for this resource. It's helpful.
