### ISSUE TITLE
MG Review

### ISSUE THREAD

**Issue by MinMah23** [DeeshaPatel/CAS-741-Solar-Cooker#44]
There are some suggestions here to make the MG better.

- [x] I think in AC4, "calculated" can be replace by "defined" or something like this, to make difference from AC5.
- [x] In AC6, you meant the data structure used for time vector? if yes, it might be better to mention it and make it more abstract.
- [x] In UC6 and UC7, it is mentioned that the ODEs or energy equation are reading the input file, I think "reading" is not the proper word, because they are not responsible for reading the input file, if I got you right, "defined" might be better. 
- [x] In 7.2.2, Services section, you wrote "calculate", but as I understand your project, this module defines the ODE according to the input parameters.
- [x] In 7.2.3, it can be useful to add the format of the input file here.

**Comment by DeeshaPatel** [comment]
My UC6 and UC7 says that it will continue to read different inputs from the file only.

**Comment by DeeshaPatel** [comment]
My 7.2.2 Energy Equation Module calculates the energy in fluid. My ODEs are defined using ODE solver module and Temperature ODE Module.
