### ISSUE TITLE
MIS Review

### ISSUE THREAD

**Issue by MinMah23** [DeeshaPatel/CAS-741-Solar-Cooker#45]
- [x] List of tables is missed.
- [x] In section6, you can delete " Hardware Hiding Module" in uses subsection, because we don't have this module in this document.
- [x] In section 6, ConstValueParams is a function, but in the table the "In" field is empty. Also you define "params: An object of ConstValueParams" which the "object" is not proper.
- [x] It is better to consider that, Each access program has either an output, or a state transition and only rarely should an access program do both, so when you have transition, it's not necessary to add output and vice versa.
- [x] The energyWat in section 7, seems to be an output not a transition
- [x] Module 8, 9, and the rest of them can start in a new page.
- [x] In 9.4.2 Environment Variables, the input file should be written.
- [x] I suggest to change the name of M10 to output module, because the format is part of it.
- [x] In 10.4.2, the environmental variable is the output file. 
- [x] you can delete "Sequence Data Structure Module" in uses in section 11.
- [x] In 14.3.2. the output and exception need to be revised.
- [x] In 14.4..4, I might be wrong but I think Plot() has output not transition, also add the input of it.
- [x] you can delete section 15.
- [x] As I understood section  16 is for the details of the errors.

**Comment by DeeshaPatel** [comment]
I guess my Input Parameter Module do not need any environment variable. I have updated it.

**Comment by DeeshaPatel** [comment]
I prefer to keep Sequence Data Structure Module for easy track of different modules. So, I have added "consideration" subsection in that module to clarify the importance of the module. I have seen the same in the one of the example: https://gitlab.cas.mcmaster.ca/smiths/se2aa4_cs2me3/-/blob/master/Assignments/A3/A3P1_Spec.pdf

**Comment by DeeshaPatel** [comment]
I think you are right. But we can also add the details about possible exceptions for specific module here. Let's ask prof for the same. @smiths can you guide us for the appendix part?

**Comment by smiths** [comment]
@DeeshaPatel, yes the Appendix can be used for exceptions related to bad input.  However, you don't want to just have the table in the Appendix.  The body of the document should show some samples of how the exceptions are generated.  This is what is done in the SWHS example.  verify_params() shows some sample exceptions and then has a pointer to the appendix for further details.

**Comment by DeeshaPatel** [comment]
Ok dear @smiths. Thank you so much. I'll update my document accordingly.
