### ISSUE TITLE
Issues with Purpose of Document:

### ISSUE THREAD

**Issue by MinMah23** [DeeshaPatel/CAS-741-Solar-Cooker#5]
- [x]  As the Writing- checklist suggests, it’s better to Avoid sentences that start with “It.", you can check it again. Like “It includes a variety of parameters that attempts to define the intended functionality required.”
- [x] The rest of second paragraph after the first sentence is not related to this document, it’s about whole process and other steps, and I think it’s better to be deleted.

**Comment by smiths** [comment]
@DeeshaPatel, it is nice to see you include traceability to the commit that closes the issue!

**Comment by DeeshaPatel** [comment]
All thanks to you dear prof. You gave a perfect and helpful guidance to us.
