### ISSUE TITLE
Issues with Scope of Requirements:

### ISSUE THREAD

**Issue by MinMah23** [DeeshaPatel/CAS-741-Solar-Cooker#6]
- [x] Numerous shouldn’t start with capital letter.
- [x] The first sentence need some changes : “There are Numerous algorithm has been proposed to improve”, you can say: “Numerous algorithms have been proposed to improve or there are numerous algorithms to improve.
- [x] I don't get what you means by saying "one iteration for the reflections".

**Comment by DeeshaPatel** [comment]
Thank you so much @MinMah23 for really helpful comments. It was easy to track. 

I have updated the [SRS](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/blob/0ac1d57e09d53bd19224626a13caf6c1c1dd5227/docs/SRS/SRS.pdf) document in https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/commit/0ac1d57e09d53bd19224626a13caf6c1c1dd5227 commit for #3  #4 #5 #6 issue. 

Closing these four issues.
