### ISSUE TITLE
some minor issues

### ISSUE THREAD

**Issue by MinMah23** [DeeshaPatel/CAS-741-Solar-Cooker#7]
- [x] In section 2.3, you specified "Mechanical Engineering expected", I might be wrong, but what about Chemistry Engineering?
- [x] May be, It would be better to determine the Calculus course offered in which level is needed.
- [x] The last two sentences of section 2.4 is not related to the organization of the document.
- [x] In the section 2.4, you wrote "SWHS", you should add it to Acronym table ad expand it.
- [x] In section 3.1, you wrote "arrows indicate what data and information is passed from the user to the program", you should add about the output which passed from the program to the user.
- [x] In section 3.1, the second part should mention software responsibilities. They should end with period.
- [x] Correct the words in section 3.2 as highlighted: 
![image](https://user-images.githubusercontent.com/121309168/217699142-6ca16e68-b9d8-4612-813d-9cf5771b8a25.png)

**Comment by DeeshaPatel** [comment]
Update the [SRS](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/blob/3ee529d4fed521f20b40b2f3b7e285b556b2d33b/docs/SRS/SRS.pdf) document in [3ee529d](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/commit/3ee529d4fed521f20b40b2f3b7e285b556b2d33b) comment for issue #7.
