### ISSUE TITLE
Issues with section 4

### ISSUE THREAD

**Issue by MinMah23** [DeeshaPatel/CAS-741-Solar-Cooker#8]
- [x] Section 4.1.1, It's better to be consistent and start all the bullets with capital and end with period.
- [x] What are int1,2,3 at the picture?
- [x] In section 4.1.3,  according to your goals, the program has two outputs, but at the figure1 and system context, it was shown just one of the outputs.
- [x] What is the cooking energy in the GS2? may be it's better to tell energy or absorbed energy or saved energy.
- [x] About assumption 4, you should say, the recipient is water, I don't get why you distinguished between for this case and for us, both of them are the same.
- [x] You should mention the parameters used in A5 at the table of symbols.
- [x] In TM1,  you used parameter q, define it at the symbols.
- [x] Thermal flux is the same as heat flux which you defines at terminology part?
- [x] In TM2, you use C and Q, which are not defined at symbols. 
- [x] You have used "heat capacity", it's better to define it in the terminology part.
- [x] As I get, at the description part in TM, we should describe the equation itself, it is so practical that you wrote  about the usage of the equation at your problem but add the description too.

**Comment by DeeshaPatel** [comment]
@MinMah23  For your 4th comment, I guess Heat Energy is a perfect word in GS2. So, I am changing accordingly. The reason is: It will be heat energy in the recipient which will be use to cook the food. Thank you so much dear for correcting me.

**Comment by DeeshaPatel** [comment]
I have completed these changes in [SRS.pdf ](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/blob/7c68bf57c732023b1ea1be8be29c40e53fd99ef2/docs/SRS/SRS.pdf)file. Commit for issue #8 is [7c68bf5](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/commit/7c68bf57c732023b1ea1be8be29c40e53fd99ef2)
