### ISSUE TITLE
continue to issue #8

### ISSUE THREAD

**Issue by MinMah23** [DeeshaPatel/CAS-741-Solar-Cooker#9]
To add some points to issue #8:

- [x] I'm not sure which one is better, but I've seen that you wrote some of the Source part at the their space in tables and some as citation at the reference part. Consistency helps readability.
- [x] Some parameters in DD1 need to be defined such as Q13.
- [x] It can be helpful to add "Incidental solar radiation" definition.
- [x] Different Q are used in different DDs, I suggest to describe Qx in general and then use it in different numbers.
- [x] The constraint defined on the input in IM1, is on the parameter which is not at the inputs.
- [x] In IM1, Because Tf is the function of time, it's better to describe it as the temperature of Fluid f at the time of t.
- [x] In the IM2, correct the reference T?? at description part.
- [x] It's better to refer to A4, like you did at IM2, instead of explaining again about the using water as test.
- [x] In 4.2.6, "and" between input and output missed.
- [x] In Table1, what is n?
- [x] In Table1, What are min and max of the parameters? I couldn't find them at the document.

**Comment by DeeshaPatel** [comment]
For last question: min and max are the minimum and maximum value for the particular thing. For example, L is a length of box and that should be not too big or too small. It should be between standard solar box's minimum and maximum length.

**Comment by DeeshaPatel** [comment]
I am not clear with it: "Different Q are used in different DDs, I suggest to describe Qx in general and then use it in different numbers." All Q's have different meaning. So, I just clarified the meaning of each. I guess I don't need to add other details in it.

**Comment by DeeshaPatel** [comment]
The mentioned links are the direct weblink and citation are the books/publications. So, I guess, it's good to separate it in source.

**Comment by DeeshaPatel** [comment]
The updated [SRS.pdf](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/blob/59d4b6e5af2ef5bd3fc39fdb8c00024b38b3fbad/docs/SRS/SRS.pdf) file which address to the given issues. [59d4b6e](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/commit/59d4b6e5af2ef5bd3fc39fdb8c00024b38b3fbad)
